{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_in_progress{instance=\"todo:80\",job=\"todo\"}"
    }
   ]
  },
  {
   "title": "Total requests processed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_requests_received_total)"
    }
   ]
  },
  {
   "title": "Total todo tasks created",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "todo_tasks_created_total{instance=\"todo:80\",job=\"todo\"}"
    }
   ]
  }
 ]
}