global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "todo"
    metrics_path: /metrics
    static_configs:
      - targets: ["todo"]
  - job_name: "docker"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.1.117:9323"]
